/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.2
  Forc version: 0.68.7
  Fuel-Core version: 0.43.1
*/

import {
  Account,
  BigNumberish,
  BN,
  decompressBytecode,
  Script as __Script,
} from 'fuels';

export type ScriptInputs = [];
export type ScriptOutput = BN;

const abi = {
  "programType": "script",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "struct std::b512::B512",
      "concreteTypeId": "745e252e80bec590efc3999ae943f07ccea4d5b45b00bb6575499b64abdd3322",
      "metadataTypeId": 2
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "[_; 2]",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "__array_element",
          "typeId": 1
        }
      ]
    },
    {
      "type": "b256",
      "metadataTypeId": 1
    },
    {
      "type": "struct std::b512::B512",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    }
  ],
  "functions": [
    {
      "name": "main",
      "inputs": [],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": null
    }
  ],
  "loggedTypes": [
    {
      "logId": "8385180437869151632",
      "concreteTypeId": "745e252e80bec590efc3999ae943f07ccea4d5b45b00bb6575499b64abdd3322"
    }
  ],
  "messagesTypes": [],
  "configurables": [],
  "errorCodes": {}
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA2VTv2/TQBh9Tl2wxI/eQMFcBfVASyUkVIkiwXaWZZKQRr02QVSqjK+iQ0fLKhUbHRg6lopfY0bGy5YJdWH3n5ClQ6VYZACpVYfwXWLRqvXi7/S+773z+555fx5bgI3hM5YU7/fR4MBigwF4T+ITLE8GuusdP8HqabckT7s2zTznjQyyrDv8iOEC9ln9zlzCWqqsXVnTrqoyc15VoedGa/pa9Fpfj8r6RlqBw6q3dibrM2J7ERbNXk0XUZqqNw/SJmGvnorZJjB3b0Pw1QQs3BBxKIxuEufqZpzLiTj3GGnMFxq7RkPW2s7o3HYI6xdYxo888MNL9/1AWEWVM6Z8xqIQVuQDMz7DF1iDrw4KH0qMr3WxLmxL5RAyaGcq0EIutTOqK/wIF3lXyDehAuNFu6NCuLwCpAKl2/4DbAtwmusQ1jIY1S2q6f7DepfqpKiV8ZgfXuJfJv4fxM+o9xn1sijog3x9GNX03IJlr/A/MPt9RJreFGkyf2HoHfXSTkm70fbUstGg3fjClQ3dMeeooe9Eb7VLe7prZlnUxKS/be482hF9w5T/EakibP0KZpXZUSi4TEBcGfnosTAUIx3dj3NxP853puM88Uh/r/guh/r+e8OqnngHvNg3Pp8ofCffv5H/L49Be8DE2R5Q4UELvNxFWrExS56ajMW9ZCxdtBHn83bcw7jKTQ4oFyZ/vufyv8C+mT1hBTcmCu7pc9ybPNgbctOsVLWWW/DMGZ5oSY/LKuWtoQXpOLIuHFX3TMYo44Ly47FCZ/OczrTRKdOftfVm5vHOz197/wC38FJ7eAMAAA==');

export class Script extends __Script<ScriptInputs, ScriptOutput> {

  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(wallet: Account) {
    super(bytecode, abi, wallet);
  }
}
